BBBB BBBB BBBBBB BBBBBB

BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

BBBBBBB BB BBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BB BBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BB BBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BB BBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BB BBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BB BBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BB BBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BB BBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BB BBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXFFFFFFFFFFFFFFFX XXXXXFFFFFFFFFFFFFFFFFFFFX BB BBBBBXXXXXXXXBBBBB XXXXXXXXX XXXXXXXXXXX BB BBBBBXXBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XX XXXXXXXXXXX XXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX
        XXXXXXXFFFFFFFFFF BBBBB BBBBBBBBBBBBBXXXXXXXX

        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

        BBB BBBBB BB BBBBBB
            XXXXX XXXXXXX XXXXXXXXXXXXXXXXX
        BBBBBB

        BBB BBBBBBB BB BBBBBBBBBBBBB
            XXXXX BB BBBBBBBBBBBXXXXXXBBBBB BB BBBBBBBBBBBBXXXXXXXBBBBB BB BBBBBBBBBBBBXXXXXXXBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX
        BBBBBB

        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

        BBB BBBBBB BB BBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB

        BBBBB BBBBBBBBBBBBBBBBBB

        BBBBB BBBBBBBBBBBBBBBBB

        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX

        BBBBB BBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        BBBBBBBB

        BBBBB BBBBBBBBB
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBB
    XXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBXXXXX BBBBBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXBBB BBBX
          XXXXXXXXX
                  BB BBBBXXXXXXXXXX XBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBXXBBBBB
                  XXXXXXXXXXXXXXXXXX XXXXXX
                  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX X XXXX
                  XX
          XXXXXXXX
                  XXXXXXXXX X BB BBBBXXXXXXXXXXXXXXX XX XBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBXBBBBXXBBBBBX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXX X XXXXXX
                 X
    X
        BB BBBBBB
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX X
                    XXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFF FFFF FFFFFX
                    XXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFF FFFF FFFFFX
                    XXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFF FFFF FFFFFX

                    BB BBBBBBBBBBBBB
                        XXXXXXXXXXXXXXXX X
                    BBBBB

                    BBB BBBBB BBBBBBB BB BBBBBBBBBBBB
                        BBB BBBBBBB BBBBB BB BBBBBBBBBBBBB
                            XXXXXXXXXX X
                        BBBBBB
                    BBBBBB
                X
            XXXXXXXX
        BBBBB

        BBBBB BBBBBBBBBBBB

        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXXX

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX
XXXXXXX
