# Generated by Django 5.2.12 on 2026-04-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_client_options_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to suspend all tenant operations.', verbose_name='active status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Official display name of the tenant.', max_length=100, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(help_text='Internal identifier used to isolate data. Must be unique and lowercase.', max_length=63, unique=True, verbose_name='tenant ID'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(help_text='The URL where users will access the booking portal (e.g., tenant.com).', max_length=253, unique=True, verbose_name='web address'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='If multiple domains exist, this is the main address.', verbose_name='primary URL'),
        ),
    ]
