BBBBBBB BBBBBBBBBBBBBBBBB BBBB BBBBBB BBBB

BBBBB BBBBBBB BBBBBBBB X BBBBB X  _('Django site admin') BBBBBBBB

XXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX gettext(u'From') X XXXXXXXXXXXXXXX gettext(u'To') XX

BBBBB BBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBB

XXXX XXXX XXXXXXXX XXXXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXX XXXXXX XXXXXX XXXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB

