# Generated by Django 5.2.12 on 2026-04-01 02:24

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_model', models.CharField(choices=[('PRE-PAID', 'Pre-payment'), ('POST-PAID', 'Post-payment')], default='POST-PAID', max_length=10)),
                ('allow_overlap', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduler.eventtype')),
            ],
        ),
    ]
