# Generated by Django 5.2.12 on 2026-04-01 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_booking_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(default='oklch(0.81 0.11 236)', help_text='Custom brand color in OKLCH or HEX format.', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid OKLCH color or HEX code.', regex='^(oklch\\(.*\\)|#[0-9a-fA-F]{3,6})$')]),
        ),
    ]
