# Generated by Django 5.2.12 on 2026-04-01 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_companyprofile_brand_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(default='oklch(0.81 0.11 236)', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX code or OKLCH function (e.g. #87d1ff or oklch(0.81 0.11 236))', regex='^(#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6}|oklch\\([\\d.]+\\s[\\d.]+\\s[\\d.]+\\))$')]),
        ),
    ]
