# Generated by Django 5.2.12 on 2026-04-01 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_companyprofile_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Business Hours',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='price',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='currency',
            field=models.CharField(default='USD', help_text="The brand's operating currency.", max_length=10),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('format_category', models.CharField(blank=True, max_length=50, null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduler.eventtype')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduler.event'),
        ),
        migrations.CreateModel(
            name='EventAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text="Start of the rule's validity.", null=True)),
                ('end_date', models.DateField(blank=True, help_text="End of the rule's validity.", null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='scheduler.event')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduler.eventavailability')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
