# Generated by Django 5.2.12 on 2026-04-01 18:11

import django.core.validators
import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_businesshours_remove_booking_event_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Availability Slot', 'verbose_name_plural': 'Availability Slots'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='businesshours',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Business Hour', 'verbose_name_plural': 'Business Hours'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventavailability',
            options={'verbose_name': 'Event Availability', 'verbose_name_plural': 'Event Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event Type', 'verbose_name_plural': 'Event Types'},
        ),
        migrations.AddField(
            model_name='businesshours',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='scheduler.companyprofile', verbose_name='company profile'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='end_time',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='event_availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduler.eventavailability', verbose_name='event availability'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='client email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='client name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduler.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid')], default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='end_time',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(default='oklch(0.81 0.11 236)', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX code or OKLCH function (e.g. #87d1ff or oklch(0.81 0.11 236))', regex='^(#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6}|oklch\\([\\d.]+\\s[\\d.]+\\s[\\d.]+\\))$')], verbose_name='brand color'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='currency',
            field=models.CharField(default='USD', help_text="The brand's operating currency.", max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Calendar ID'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe public key'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='stripe_secret_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe secret key')),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduler.eventtype', verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='format_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='format category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='end_date',
            field=models.DateField(blank=True, help_text="End of the rule's validity.", null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='scheduler.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='start_date',
            field=models.DateField(blank=True, help_text="Start of the rule's validity.", null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='allow_overlap',
            field=models.BooleanField(default=False, verbose_name='allow overlap'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='payment_model',
            field=models.CharField(choices=[('PRE-PAID', 'Pre-payment'), ('POST-PAID', 'Post-payment')], default='POST-PAID', max_length=10, verbose_name='payment model'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
