# Generated by Django 5.2.12 on 2026-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_availabilityslot_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='format_category',
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=10, verbose_name='currency'),
        ),
    ]
