# Generated by Django 5.2.12 on 2026-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_remove_event_format_category_event_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='currency',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', help_text="The brand's operating currency.", max_length=10, verbose_name='currency'),
        ),
    ]
