# Generated by Django 5.2.12 on 2026-04-01 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_event_currency_alter_companyprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='scheduler.event', verbose_name='event'),
        ),
    ]
