# Generated by Django 5.2.12 on 2026-04-01 21:11

from django.db import migrations

def migrate_slots(apps, schema_editor):
    AvailabilitySlot = apps.get_model('scheduler', 'AvailabilitySlot')
    for slot in AvailabilitySlot.objects.all():
        if slot.event_availability and slot.event_availability.event:
            slot.event = slot.event_availability.event
            slot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_availabilityslot_event'),
    ]

    operations = [
        migrations.RunPython(migrate_slots),
    ]
