# Generated by Django 5.2.12 on 2026-04-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_migrate_slots_to_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityslot',
            name='event_availability',
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=10, verbose_name='currency'),
        ),
    ]
