# Generated by Django 5.2.12 on 2026-04-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_remove_availabilityslot_event_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='scheduler.event', verbose_name='event'),
        ),
    ]
