# Generated by Django 5.2.12 on 2026-04-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_alter_availabilityslot_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='scheduler.event', verbose_name='event'),
        ),
    ]
