# Generated by Django 5.2.12 on 2026-04-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_availabilityslot_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Week Day', 'verbose_name_plural': 'Week Days'},
        ),
        migrations.AlterModelOptions(
            name='eventavailability',
            options={'verbose_name': 'Date Range', 'verbose_name_plural': 'Date Ranges'},
        ),
    ]
