# Generated by Django 5.2.12 on 2026-04-02 01:12

import django.core.validators
import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_alter_availabilityslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Bookable Slot', 'verbose_name_plural': 'Bookable Slots'},
        ),
        migrations.AlterModelOptions(
            name='businesshours',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Operating Hour', 'verbose_name_plural': 'Operating Hours'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(help_text='The date and time the appointment begins.', verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid')], default='PENDING', help_text='Confirmed bookings trigger automated notifications.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(default='oklch(0.81 0.11 236)', help_text='The main color for the booking page. Supports HEX and OKLCH format (e.g., oklch(0.8 0.1 240)).', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX code or OKLCH function (e.g. #87d1ff or oklch(0.81 0.11 236))', regex='^(#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6}|oklch\\([\\d.]+\\s[\\d.]+\\s[\\d.]+\\))$')], verbose_name='brand primary color'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', help_text='Default currency for all services offered by the company.', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='Calendar ID (usually an email address) for Google Calendar synchronization.', max_length=255, null=True, verbose_name='Google Calendar ID'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended dimensions: 200x200 pixels.', null=True, upload_to='logos/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='stripe_public_key',
            field=models.CharField(blank=True, help_text='Your Stripe Publishable Key found in the Developer Dashboard.', max_length=255, null=True, verbose_name='Stripe public key'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='stripe_secret_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Your Stripe Secret Key. This field is encrypted.', max_length=255, null=True, verbose_name='Stripe secret key')),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of the service in minutes.', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The base cost of the service.', max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='allow_overlap',
            field=models.BooleanField(default=False, help_text='Allows multiple bookings for the same time slot (useful for classes or group events).', verbose_name='allow overlap'),
        ),
        migrations.CreateModel(
            name='EventDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('is_available', models.BooleanField(default=False, help_text='If unchecked, this date will be blocked even if it falls within a valid range. If checked, it will be available even if outside valid ranges.', verbose_name='is available')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='scheduler.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'Date Override',
                'verbose_name_plural': 'Date Overrides',
                'unique_together': {('event', 'date')},
            },
        ),
    ]
