# Generated by Django 5.2.12 on 2026-04-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_alter_availabilityslot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='currency',
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='is_available',
            field=models.BooleanField(default=False, help_text='If unchecked, this date will be blocked even if it falls within a valid range. If checked, it will be available even if outside valid ranges.', verbose_name='Is available'),
        ),
    ]
