# Generated by Django 5.2.12 on 2026-04-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_remove_event_currency_alter_eventdateoverride_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdateoverride',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='eventdateoverride',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='event',
            field=models.ForeignKey(help_text="Weekly pattern for this service. If any slot is defined here, the company's global 'Operating Hours' will be ignored for this event.", on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='scheduler.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='start_date',
            field=models.DateField(blank=True, help_text="Defines the validity period of the event. Note: You still need to define 'Bookable Slots' below for these days to be active.", null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Individual date exception. It has the highest priority and overrides Date Ranges. If start/end times are set, they override weekly slots.', verbose_name='Is available'),
        ),
    ]
