# Generated by Django 5.2.12 on 2026-04-02 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_eventdateoverride_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshours',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Operating Hour (Legacy)', 'verbose_name_plural': 'Operating Hours (Legacy)'},
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='end_date',
            field=models.DateField(blank=True, help_text='Defines the end of the validity period.', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='start_date',
            field=models.DateField(blank=True, help_text='Defines the beginning of the validity period.', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Individual date exception. Highest priority override. If start/end times are set, they override weekly slots.', verbose_name='Is available'),
        ),
        migrations.CreateModel(
            name='CompanyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text='Defines the beginning of the validity period.', null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='Defines the end of the validity period.', null=True, verbose_name='end date')),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='scheduler.companyprofile', verbose_name='company profile')),
            ],
            options={
                'verbose_name': 'Company Date Range',
                'verbose_name_plural': 'Company Date Ranges',
            },
        ),
        migrations.CreateModel(
            name='CompanyWeekdaySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_slots', to='scheduler.companyprofile', verbose_name='company profile')),
            ],
            options={
                'verbose_name': 'Business Hour',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['weekday', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_available', models.BooleanField(default=False, help_text='Individual date exception. Highest priority override. If start/end times are set, they override weekly slots.', verbose_name='Is available')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='scheduler.companyprofile', verbose_name='company profile')),
            ],
            options={
                'verbose_name': 'Company Date Override',
                'verbose_name_plural': 'Company Date Overrides',
                'unique_together': {('company_profile', 'date')},
            },
        ),
    ]
