# Generated by Django 5.2.12 on 2026-04-02 13:20

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_alter_businesshours_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_event_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier of the event in the Google Calendar.', max_length=255, null=True, verbose_name='Google Event ID'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='google_calendar_credentials',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text="JSON credentials for the Google Service Account associated with this tenant's calendar (must be copied from the Service Account JSON key).", null=True, verbose_name='Google Calendar credentials')),
        ),
    ]
