# Generated by Django 5.2.12 on 2026-04-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_booking_google_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_sync_error',
            field=models.TextField(blank=True, help_text='Latest error message encountered during synchronization.', null=True, verbose_name='Google Sync Error'),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DISABLED', 'Disabled')], default='PENDING', help_text='Current status of the Google Calendar synchronization.', max_length=20, verbose_name='Google Sync Status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date and time this booking was last successfully synchronized.', null=True, verbose_name='Last Synced At'),
        ),
    ]
