# Generated by Django 5.2.12 on 2026-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_booking_google_sync_error_booking_google_sync_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, help_text='The phone number of the client.', max_length=20, null=True, verbose_name='client phone'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Main business contact email shown to clients.', max_length=254, null=True, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Main business contact phone shown to clients.', max_length=20, null=True, verbose_name='contact phone'),
        ),
    ]
