# Generated by Django 5.2.12 on 2026-04-03 17:18

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_booking_client_phone_companyprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='stripe_webhook_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Your Stripe Webhook Secret for signature verification.', max_length=255, null=True, verbose_name='Stripe webhook secret')),
        ),
    ]
