# Generated by Django 5.2.12 on 2026-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_companyprofile_stripe_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='availability_free_label',
            field=models.CharField(default='Free', help_text='Text to show for the color label when a slot is free.', max_length=100, verbose_name='availability free label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='availability_no_free_label',
            field=models.CharField(default='Full', help_text='Text to show for the color label when a slot is no longer free.', max_length=100, verbose_name='availability no free label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='availability_regular_label',
            field=models.CharField(default='Regular', help_text='Text to show for the color label when a slot has some bookings.', max_length=100, verbose_name='availability regular label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='event_label',
            field=models.CharField(default='Event', help_text='The name of the events in the UI (e.g., Tour, Service, Consultation).', max_length=100, verbose_name='event label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='event_type_label',
            field=models.CharField(default='Event Type', help_text='Label for each Event Type in the UI (e.g., Tour Type, Service Category).', max_length=100, verbose_name='event type label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='extras_label',
            field=models.CharField(default='Extras', help_text='Label for special petitions or extras in the service.', max_length=100, verbose_name='extras label'),
        ),
    ]
