# Generated by Django 5.2.12 on 2026-04-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_companyprofile_availability_free_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='google_calendar_credentials',
        ),
    ]
